use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::Result;

use crate::utils::command::append_ubt_target_selection;
use crate::utils::file::atomic_copy;
use crate::utils::logger::Logger;
use crate::utils::unreal_paths::resolve_ubt_path;

use super::engine_resolver::EngineResolver;
use super::process_runner::ProcessRunner;
use super::project_path_resolver::ProjectPathResolver;

pub struct CompileCommandsGenerator;

impl CompileCommandsGenerator {
    pub fn generate(
        config: &str,
        platform: &str,
        project: Option<&str>,
        engine_path: Option<&str>,
        include_plugin_sources: bool,
        include_engine_sources: bool,
        use_engine_includes: bool,
        ubt_args: &[String],
    ) -> Result<PathBuf> {
        let (project_path, engine) =
            EngineResolver::resolve_project_and_engine(project, engine_path)?;

        let ubt_path = resolve_ubt_path(&engine)?;

        Self::generate_with_paths(
            config,
            platform,
            &project_path,
            &engine,
            &ubt_path,
            include_plugin_sources,
            include_engine_sources,
            use_engine_includes,
            ubt_args,
        )
    }

    pub(crate) fn generate_with_paths(
        config: &str,
        platform: &str,
        project_path: &Path,
        engine: &Path,
        ubt_path: &Path,
        include_plugin_sources: bool,
        include_engine_sources: bool,
        use_engine_includes: bool,
        ubt_args: &[String],
    ) -> Result<PathBuf> {
        let project_dir = ProjectPathResolver::project_dir(project_path);

        let mut args = vec![
            "-mode=GenerateClangDatabase".to_string(),
            format!("-Project={}", project_path.display()),
            platform.to_string(),
            config.to_string(),
        ];

        if include_plugin_sources {
            args.push("-IncludePluginSources".to_string());
        }
        if include_engine_sources {
            args.push("-IncludeEngineSources".to_string());
        }
        if use_engine_includes {
            args.push("-UseEngineIncludes".to_string());
        }
        append_ubt_target_selection(&mut args, ubt_args);

        Logger::info(&format!(
            "Generating compile commands ({platform} {config})"
        ));

        let mut command = Command::new(ubt_path);
        command.args(&args);
        let output = ProcessRunner::capture(&mut command)?;

        let stdout = &output.stdout;
        for line in stdout.lines() {
            Logger::debug(line);
        }

        if output.exit_code != 0 {
            anyhow::bail!(
                "UBT exited with code {}:\n{}\n{stderr}",
                output.exit_code,
                stdout.trim_end(),
                stderr = output.stderr
            );
        }

        // Relocate compile_commands.json
        let source_cc = engine.join("compile_commands.json");
        let dest_cc = project_dir.join("compile_commands.json");

        if source_cc.exists() {
            if dest_cc.exists() || std::fs::rename(&source_cc, &dest_cc).is_err() {
                atomic_copy(&source_cc, &dest_cc)?;
                std::fs::remove_file(&source_cc)?;
            }
        } else if dest_cc.exists() {
            // Already in the right place
        } else {
            anyhow::bail!(
                "compile_commands.json was not generated by UBT in {}",
                engine.display()
            );
        }

        Ok(dest_cc)
    }
}
